### ISSUE TITLE
Cannot call the module

### ISSUE THREAD

**Issue by cooperdk** [geraldlnj/duplicate-video-finder#1]
```
from dvf import DuplicateFinder
duplicate_finder = DuplicateFinder('(dir)')
```

**does not work.**

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'module' object is not callable

**This works partly:**

```
>>> from DuplicateFinder import DuplicateFinder
>>> duplicate_finder = DuplicateFinder('(dir)')
```

**But then:**

`>>> DuplicateFinder.find_dups()`

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: find_dups() missing 1 required positional argument: 'self'

This yields no error, but also no result (other than None). It takes three seconds with a 200-video library with files from 200 to 1800 megabyte:

`duplicate_finder = DuplicateFinder('(dir)').find_dups()`

Running Python 3.8, on Windows. Dependencies are installed. This is a module call issue.

EDIT: Made it work by calling duplicate_finder.get_dups() and duplicate_finder.get_results() instead of the main module as instructed.
But it returns ZERO results and takes about 30 seconds for a library of 7000 video files more than 4 terabytes in size.
There's something wrong with this project.

**Comment by ghost** [comment]
Hey, thanks for checking out this project of mine!

Regarding the import: I'm not sure where you got `dvf` from, but your second import should be correct.

Regarding the calling of the function: My bad, that's mistake in my readme. I'm at work now so I can't help to debug for now, but you can refer to the bottom of the main module file to see examples of how to use it: https://github.com/geraldlnj/duplicate-video-finder/blob/3070ea6166150c5ae8a628a5d169b98595b2dac8/DuplicateFinder.py#L220-L223

Otherwise, could you share your folder structure? Perhaps you aren't running it in recursive mode?

**Comment by ghost** [comment]
I see that you're creating the `DuplicateFinder` object with no args for recursive, and it defaults to `recursive=False`, maybe try it with 

```
duplicate_finder = DuplicateFinder('(dir)', True)
duplicate_finder.find_dups()
```

Finally, you need to call `.get_results()` to view the output:
```
duplicate_finder.get_results()
```
